//! Aggregated integration-test target for the `tests/raw_coverage/` suites.
//!
//! Each `tests/raw_coverage/*_raw_coverage_e2e.rs` file is included here as a
//! module instead of being its own `tests/*.rs` target. Cargo builds one test
//! binary for this file rather than ~76, so the (large) `openhuman` rlib is
//! linked once instead of once per file. The module list is generated by
//! `build.rs` (see `raw_coverage_mods.rs`) so new files are picked up
//! automatically.
//!
//! Each included file keeps its own `#![cfg(...)]` gates — as module-level
//! inner attributes they conditionally compile just that module, matching the
//! per-target behaviour these files had as standalone binaries.

// Helper fns/imports that were "used" inside a file's own standalone test
// binary can read as dead once every file shares one crate root here (e.g. a
// helper only reached by a `#[cfg]`-gated test). These are coverage suites, not
// production code, so silence the noise rather than churn 76 files.
#![allow(dead_code)]

use std::sync::OnceLock;

/// Process-global env lock shared by every aggregated suite that mutates
/// process-global env (`OPENHUMAN_WORKSPACE`, `HOME`, `BACKEND_URL`, …).
///
/// Before these files were collapsed into this single binary they ran as
/// separate processes, so each file's own env lock was sufficient — different
/// files could never race because they had independent environments. Now that
/// they share one process, libtest runs them concurrently and per-file locks no
/// longer mutually exclude. Each file's local env lock is redefined to a
/// `&`-reference to this one static, so all env mutations across all aggregated
/// suites serialize on a single mutex while non-env tests keep running in
/// parallel. The lock is a `tokio::sync::Mutex`: it is never poisoned, so a
/// panicking test cannot wedge the whole suite, and an async test may hold its
/// guard across `.await`. Synchronous tests take it with `blocking_lock()`,
/// async tests with `lock().await`.
pub static SHARED_ENV_LOCK: OnceLock<tokio::sync::Mutex<()>> = OnceLock::new();

/// Serializes aggregated suites that reach the Composio connector module.
///
/// The module is loaded once per process and holds exactly one route, so two
/// tests that point it at different routes (backend vs direct mode) race when
/// run concurrently: one reconfigures the module mid-call and the other sees
/// the wrong route. The core's own unit tests serialize on `module_guard`,
/// which is `cfg(test)`-only; this is the integration-binary equivalent.
pub static CONNECTOR_MODULE_LOCK: tokio::sync::Mutex<()> = tokio::sync::Mutex::const_new(());

/// The TinyHumans backend transport for every aggregated suite that boots the
/// core in-process and reaches the mock backend: call
/// `crate::tinyhumans_boot::boot()` from the suite's fixture (or each test).
/// The core carries no backend client of its own.
#[path = "support/tinyhumans_boot.rs"]
pub mod tinyhumans_boot;

/// The shared `EnvVarGuard` (set / unset one var, restore on drop). It does not
/// lock: suites hold [`SHARED_ENV_LOCK`] through their own `env_lock()`.
#[path = "support/env_guard.rs"]
pub mod env_guard;
/// The RPC bearer and JSON-RPC helpers some suites share (see `support/`).
#[path = "support/rpc_auth.rs"]
pub mod rpc_auth;
#[path = "support/rpc_harness.rs"]
pub mod rpc_harness;

include!(concat!(env!("OUT_DIR"), "/raw_coverage_mods.rs"));
